import fs from 'node:fs'
import fsp from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import zlib from 'node:zlib'
import { promisify } from 'node:util'
import { log } from './util/log'
import { loadSavedSavesDir, saveSavesDir } from './settings'

const gzip = promisify(zlib.gzip)
const gunzip = promisify(zlib.gunzip)

export interface ScanInfo {
  name: string                  // folder name (sanitised server host)
  path: string                  // absolute path
  hasOverworld: boolean
  hasNether: boolean
  hasEnd: boolean
  regionFileCount: number       // .mca files across all dimensions
  lastModified: number          // unix ms
}

/**
 * List every saved scan in the user's scans directory. A "scan" is any
 * subfolder that has at least a `region/` directory with `.mca` files.
 */
export async function listScans(scansDir: string): Promise<ScanInfo[]> {
  let entries: fs.Dirent[]
  try {
    entries = await fsp.readdir(scansDir, { withFileTypes: true })
  } catch {
    return []
  }

  const out: ScanInfo[] = []
  for (const e of entries) {
    if (!e.isDirectory()) continue
    const root = path.join(scansDir, e.name)
    const info = await inspectScan(root, e.name)
    if (info) out.push(info)
  }
  out.sort((a, b) => b.lastModified - a.lastModified)
  return out
}

async function inspectScan(root: string, name: string): Promise<ScanInfo | null> {
  const overworld = path.join(root, 'region')
  const nether    = path.join(root, 'DIM-1', 'region')
  const end       = path.join(root, 'DIM1', 'region')

  const has = async (p: string) => {
    try { const s = await fsp.stat(p); return s.isDirectory() } catch { return false }
  }
  const countMca = async (p: string) => {
    try {
      const f = await fsp.readdir(p)
      return f.filter(n => n.endsWith('.mca')).length
    } catch { return 0 }
  }

  const [hasOverworld, hasNether, hasEnd] = await Promise.all([has(overworld), has(nether), has(end)])
  const vanillaCounts = await Promise.all([countMca(overworld), countMca(nether), countMca(end)])

  // Also look for datapack-dim region files. Two layouts in the wild:
  //   - canonical: dimensions/<ns>/<name>/region/*.mca   (v0.9.7+)
  //   - legacy:    dimensions/<ns>/<name>/*.mca          (pre-fix scans)
  // Count both so old captures don't appear empty.
  let customCount = 0
  try {
    const dimsDir = path.join(root, 'dimensions')
    const namespaces = await fsp.readdir(dimsDir, { withFileTypes: true })
    for (const ns of namespaces) {
      if (!ns.isDirectory()) continue
      const dims = await fsp.readdir(path.join(dimsDir, ns.name), { withFileTypes: true })
      for (const dim of dims) {
        if (!dim.isDirectory()) continue
        const dimRoot = path.join(dimsDir, ns.name, dim.name)
        customCount += await countMca(path.join(dimRoot, 'region'))
        customCount += await countMca(dimRoot)
      }
    }
  } catch {}

  const regionFileCount = vanillaCounts.reduce((a, b) => a + b, 0) + customCount
  if (regionFileCount === 0) return null

  let lastModified = 0
  try { lastModified = (await fsp.stat(root)).mtimeMs } catch {}

  return { name, path: root, hasOverworld, hasNether, hasEnd, regionFileCount, lastModified }
}

export function defaultSavesDir(): string {
  // Prefer the user's last-chosen folder (e.g. an ATLauncher instance) so
  // transforms keep landing in the same MC install across restarts.
  const saved = loadSavedSavesDir()
  if (saved) return saved
  // Standard Windows MC location; user can override at transform time.
  const appdata = process.env.APPDATA
  if (appdata) return path.join(appdata, '.minecraft', 'saves')
  // mac/linux fallbacks
  if (process.platform === 'darwin') return path.join(os.homedir(), 'Library', 'Application Support', 'minecraft', 'saves')
  return path.join(os.homedir(), '.minecraft', 'saves')
}

export interface TransformOpts {
  scanPath: string              // source folder (one of the entries from listScans)
  destName: string              // target world name inside saves/
  savesDir?: string             // override Minecraft saves location
  voidUnscanned: boolean        // make missing chunks render as void instead of vanilla terrain
}

export interface TransformResult {
  ok: boolean
  destPath?: string
  outputCopyPath?: string
  error?: string
}

function defaultOutputDir(): string {
  return path.join(os.homedir(), 'Documents', 'ChunkScribe', 'worlds')
}

/**
 * Copy a scan into Minecraft's saves folder so it shows up in singleplayer.
 * Optionally rewrites level.dat to use a void worldgen, so chunks you never
 * captured stay empty instead of being regenerated by vanilla worldgen — same
 * effect as mircokroon's tool.
 */
export async function transformToWorld(opts: TransformOpts): Promise<TransformResult> {
  const savesDir = opts.savesDir || defaultSavesDir()
  // Remember the chosen folder so the next transform defaults to it,
  // even after a proxy restart.
  if (opts.savesDir) saveSavesDir(opts.savesDir)
  const cleanName = sanitizeName(opts.destName) || 'ChunkScribe World'
  const destPath = path.join(savesDir, cleanName)

  try {
    if (!(await fsp.stat(opts.scanPath)).isDirectory()) {
      return { ok: false, error: 'scan path is not a directory' }
    }
  } catch {
    return { ok: false, error: 'scan path does not exist' }
  }

  try {
    await fsp.mkdir(savesDir, { recursive: true })
    // Refuse to overwrite an existing world — too easy to clobber by accident.
    try {
      await fsp.access(destPath)
      return { ok: false, error: `"${cleanName}" already exists in saves; pick a different name` }
    } catch {}
    await fsp.cp(opts.scanPath, destPath, { recursive: true })
    log.info(`transformed ${opts.scanPath} -> ${destPath}`)
    // Custom dims (gridlock:nether, gridlock:overworld, gridlock:end) stay
    // put in dimensions/<ns>/<name>/region. The chunkscribe datapack defines
    // each dim with its captured dim_type, so MC loads them at the right
    // Y range. The old behaviour squashed them into DIM-1/DIM1/root which
    // re-bound them to vanilla dim_types — Gridlock's nether built on
    // Y -64..60 then floated at the wrong height in vanilla nether
    // (min_y=0, height=128). Only filter out lobby-like dims.
    await cleanLobbyDims(destPath)
  } catch (e) {
    return { ok: false, error: `copy failed: ${(e as Error).message}` }
  }

  if (opts.voidUnscanned) {
    try {
      await patchLevelDatForVoid(destPath, cleanName)
      log.info(`level.dat patched to void-around-scanned`)
    } catch (e) {
      log.warn(`void-patch failed: ${(e as Error).message}`)
    }
  } else {
    try {
      await patchLevelDatName(destPath, cleanName)
    } catch (e) {
      log.warn(`level.dat rename failed: ${(e as Error).message}`)
    }
  }

  // Bundle the captured resource pack(s) into the world. Modern MC reads
  // `<world>/resources.zip` automatically; without it, custom-modeled
  // blocks (chests, furniture, etc.) on servers that use heavy resource
  // packs render as invisible — the block model is overridden to empty
  // and the visible appearance comes from pack assets only.
  try {
    const packsDir = path.join(opts.scanPath, 'resourcepacks')
    if (await fsp.stat(packsDir).then(s => s.isDirectory()).catch(() => false)) {
      const { bundlePacksIntoWorld } = await import('./capture/resourcePacks')
      const r = await bundlePacksIntoWorld(packsDir, destPath)
      if (r.bundled) log.info(`bundled resource pack into world: <world>/resources.zip (+${r.copied} extra)`)
    }
  } catch (e) {
    log.warn(`bundle resource pack failed: ${(e as Error).message}`)
  }

  // Secondary copy into Documents/ChunkScribe/worlds/<name> so the user keeps
  // a portable archive even after MC's saves folder rotates or they delete
  // the singleplayer world.
  let outputCopyPath: string | undefined
  try {
    const outRoot = defaultOutputDir()
    await fsp.mkdir(outRoot, { recursive: true })
    const outPath = path.join(outRoot, cleanName)
    // overwrite-safe: drop any prior copy with the same name first
    try { await fsp.rm(outPath, { recursive: true, force: true }) } catch {}
    await fsp.cp(destPath, outPath, { recursive: true })
    outputCopyPath = outPath
    log.info(`also copied to output archive: ${outPath}`)
  } catch (e) {
    log.warn(`output-archive copy failed: ${(e as Error).message}`)
  }

  return { ok: true, destPath, outputCopyPath }
}

function sanitizeName(s: string): string {
  return s.replace(/[\\\/:*?"<>|]+/g, '_').trim()
}

let nbt: any
try { nbt = require('prismarine-nbt') } catch {}

async function readLevelDat(dir: string): Promise<any | null> {
  if (!nbt) return null
  const p = path.join(dir, 'level.dat')
  let buf: Buffer
  try { buf = await fsp.readFile(p) } catch { return null }
  const raw = buf[0] === 0x1f && buf[1] === 0x8b ? await gunzip(buf) : buf
  return nbt.parseUncompressed(raw, 'big')
}

async function writeLevelDat(dir: string, tag: any) {
  const uncompressed = nbt.writeUncompressed(tag, 'big')
  const data: Buffer = Buffer.isBuffer(uncompressed) ? uncompressed : Buffer.from(uncompressed)
  const gz = await gzip(data)
  await fsp.writeFile(path.join(dir, 'level.dat'), gz)
}

async function patchLevelDatName(dir: string, name: string) {
  if (!nbt) return
  const tag = await readLevelDat(dir); if (!tag) return
  const data = tag.value?.Data?.value
  if (!data) return
  data.LevelName = { type: 'string', value: name }
  // The saver writes a full WorldGenSettings.dimensions compound with the
  // vanilla 3 dims AND every custom dim the player visited (pointing at
  // the captured dim_type). DO NOT strip it here — that drops the custom
  // dims back to undefined and leaves the chunks in dimensions/<ns>/<dim>/
  // orphaned. The chunkscribe datapack defines the same dims for
  // redundancy, but level.dat is the source of truth on first load.
  await enableChunkscribePack(tag)
  await writeLevelDat(dir, tag)
}

/** Enable the chunkscribe datapack the saver wrote into <world>/datapacks/.
 *  Custom biomes (and server-overridden vanilla biome colors) only take
 *  effect if the datapack is in Data.DataPacks.Enabled. */
async function enableChunkscribePack(tag: any) {
  try {
    const mod = await import('./world/datapack')
    mod.enableDatapackInLevelDat(tag)
  } catch (e) {
    log.warn(`enable datapack failed: ${(e as Error).message}`)
  }
}

/**
 * Void-mode level.dat patch. The saver already writes a full WGS compound
 * with void-flat overworld + nether + end + every custom dim the player
 * visited. Previously we REPLACED that with just the three vanilla dims,
 * which dropped every gridlock:* entry → MC re-generated minecraft:overworld
 * as a void-flat and spawned the player at (0, -6, 0) in the void.
 *
 * Now we just patch the LevelName and switch the vanilla 3 dims' generators
 * to void-flat (in case the saver wrote them with `minecraft:noise` for the
 * non-void path); the saver's custom-dim entries stay untouched.
 */
async function patchLevelDatForVoid(dir: string, name: string) {
  if (!nbt) return
  const tag = await readLevelDat(dir)
  if (!tag) return
  const data = tag.value?.Data?.value
  if (!data) return

  data.LevelName = { type: 'string', value: name }

  const dims = data.WorldGenSettings?.value?.dimensions?.value
  if (dims) {
    for (const k of ['minecraft:overworld', 'minecraft:the_nether', 'minecraft:the_end'] as const) {
      dims[k] = voidDimension(k)
    }
  }

  await enableChunkscribePack(tag)
  await writeLevelDat(dir, tag)
}

/**
 * Drop dimension folders that look like server-side lobbies / waiting rooms.
 * The datapack approach (default since v0.9.20) preserves every other custom
 * dim verbatim — we only remove lobby junk so the world isn't cluttered with
 * empty void chunks the player can teleport into by accident.
 */
async function cleanLobbyDims(root: string): Promise<void> {
  const SKIP = /\b(limbo|lobby|hub|spawn_area|waiting|queue|game_lobby)\b/i
  const dimsDir = path.join(root, 'dimensions')
  let nsEntries: fs.Dirent[]
  try { nsEntries = await fsp.readdir(dimsDir, { withFileTypes: true }) }
  catch { return }
  for (const ns of nsEntries) {
    if (!ns.isDirectory()) continue
    const nsPath = path.join(dimsDir, ns.name)
    let dims: fs.Dirent[]
    try { dims = await fsp.readdir(nsPath, { withFileTypes: true }) } catch { continue }
    for (const dim of dims) {
      if (!dim.isDirectory()) continue
      const tag = `${ns.name}/${dim.name}`.toLowerCase()
      if (SKIP.test(tag)) {
        try { await fsp.rm(path.join(nsPath, dim.name), { recursive: true, force: true }) } catch {}
        log.info(`removed lobby-like dim: ${ns.name}:${dim.name}`)
      }
    }
  }
}

/**
 * LEGACY (pre-v0.9.20): walk dimensions/<ns>/<name>/ under the destination
 * and move each datapack dim's region files into the vanilla folder
 * (DIM-1 / DIM1 / root) that matches its name. Kept for reference / future
 * "vanilla-mode" transform flag; not called from the default code path.
 *
 * Heuristic: name (case-insensitive, ns part included) containing "nether"
 * → DIM-1, "end" → DIM1, "overworld"/anything else → root.
 * Where two dims map to the same target we merge: chunks one dim has but
 * the other doesn't are kept; collisions favour the file that's already
 * there (first-write-wins). Empty parent folders are cleaned up.
 */
async function remapCustomDimensions(root: string): Promise<string[]> {
  const dimsDir = path.join(root, 'dimensions')
  let nsEntries: fs.Dirent[]
  try { nsEntries = await fsp.readdir(dimsDir, { withFileTypes: true }) }
  catch { return [] }

  const remapped: string[] = []
  // Collect every (ns, dim) pair with its file count first so we can sort.
  // The remap is FIRST-WRITE-WINS so the dim we process first claims each
  // region file. If 'gridlock:limbo' (mostly empty) processes before
  // 'gridlock:overworld' (the real map), limbo's void chunks squat in the
  // region slots and the real chunks get rejected. Solution: process the
  // biggest dim per target FIRST. Bonus: outright skip dims whose name
  // strongly suggests they're a lobby/limbo (rarely worth keeping anyway).
  const SKIP_NAMES = /\b(limbo|lobby|hub|spawn_area|waiting|queue|game_lobby)\b/i

  type DimPlan = {
    ns: string
    name: string
    dimRoot: string
    sources: string[]
    target: string
    fileCount: number
  }
  const plans: DimPlan[] = []

  for (const ns of nsEntries) {
    if (!ns.isDirectory()) continue
    const nsPath = path.join(dimsDir, ns.name)
    let dimEntries: fs.Dirent[]
    try { dimEntries = await fsp.readdir(nsPath, { withFileTypes: true }) }
    catch { continue }

    for (const dim of dimEntries) {
      if (!dim.isDirectory()) continue
      const tag = `${ns.name}/${dim.name}`.toLowerCase()
      if (SKIP_NAMES.test(tag)) {
        log.info(`remap: skipping lobby-like dim "${ns.name}:${dim.name}"`)
        // still tidy up so it doesn't ship as a ghost dim folder
        try { await fsp.rm(path.join(nsPath, dim.name), { recursive: true, force: true }) } catch {}
        continue
      }
      const dimRoot = path.join(nsPath, dim.name)
      const sources: string[] = []
      try { if ((await fsp.stat(path.join(dimRoot, 'region'))).isDirectory()) sources.push(path.join(dimRoot, 'region')) } catch {}
      sources.push(dimRoot)

      let target: string
      if (tag.includes('nether'))         target = path.join(root, 'DIM-1', 'region')
      else if (tag.includes('end'))       target = path.join(root, 'DIM1',  'region')
      else                                target = path.join(root, 'region')

      // Count .mca files this dim contributes for sort priority.
      let fileCount = 0
      for (const src of sources) {
        try { fileCount += (await fsp.readdir(src)).filter(f => f.endsWith('.mca')).length } catch {}
      }
      plans.push({ ns: ns.name, name: dim.name, dimRoot, sources, target, fileCount })
    }
  }

  // Biggest dim first → real map wins region slots.
  plans.sort((a, b) => b.fileCount - a.fileCount)

  for (const p of plans) {
    await fsp.mkdir(p.target, { recursive: true })
    let moved = 0
    for (const src of p.sources) {
      let files: string[] = []
      try { files = (await fsp.readdir(src)).filter(f => f.endsWith('.mca')) } catch {}
      for (const f of files) {
        const srcFile = path.join(src, f)
        const dst = path.join(p.target, f)
        try { await fsp.access(dst); continue } catch {}
        try { await fsp.rename(srcFile, dst); moved++ }
        catch {
          try { await fsp.copyFile(srcFile, dst); await fsp.unlink(srcFile); moved++ } catch {}
        }
      }
    }
    try { await fsp.rm(p.dimRoot, { recursive: true, force: true }) } catch {}
    remapped.push(`${p.ns}:${p.name} (${p.fileCount}f) -> ${path.relative(root, p.target)} (${moved} moved)`)
  }

  // Tidy: remove now-empty namespace folders + dimensions/ wrapper.
  for (const ns of nsEntries) {
    const nsPath = path.join(dimsDir, ns.name)
    try {
      const left = await fsp.readdir(nsPath)
      if (left.length === 0) await fsp.rmdir(nsPath)
    } catch {}
  }
  try {
    const left = await fsp.readdir(dimsDir)
    if (left.length === 0) await fsp.rmdir(dimsDir)
  } catch {}
  return remapped
}

function voidDimension(typeId: string): any {
  return {
    type: 'compound',
    value: {
      type: { type: 'string', value: typeId },
      generator: {
        type: 'compound',
        value: {
          type:     { type: 'string', value: 'minecraft:flat' },
          settings: {
            type: 'compound',
            value: {
              biome:    { type: 'string', value: 'minecraft:the_void' },
              features: { type: 'byte', value: 0 },
              lakes:    { type: 'byte', value: 0 },
              layers:   { type: 'list', value: { type: 'end', value: [] } },
              structure_overrides: { type: 'list', value: { type: 'end', value: [] } },
            },
          },
        },
      },
    },
  }
}
