import fs from 'node:fs'
import fsp from 'node:fs/promises'
import path from 'node:path'
import os from 'node:os'
import zlib from 'node:zlib'
import { promisify } from 'node:util'
import { log } from './util/log'

const gzip = promisify(zlib.gzip)
const gunzip = promisify(zlib.gunzip)

export interface ScanInfo {
  name: string                  // folder name (sanitised server host)
  path: string                  // absolute path
  hasOverworld: boolean
  hasNether: boolean
  hasEnd: boolean
  regionFileCount: number       // .mca files across all dimensions
  lastModified: number          // unix ms
}

/**
 * List every saved scan in the user's scans directory. A "scan" is any
 * subfolder that has at least a `region/` directory with `.mca` files.
 */
export async function listScans(scansDir: string): Promise<ScanInfo[]> {
  let entries: fs.Dirent[]
  try {
    entries = await fsp.readdir(scansDir, { withFileTypes: true })
  } catch {
    return []
  }

  const out: ScanInfo[] = []
  for (const e of entries) {
    if (!e.isDirectory()) continue
    const root = path.join(scansDir, e.name)
    const info = await inspectScan(root, e.name)
    if (info) out.push(info)
  }
  out.sort((a, b) => b.lastModified - a.lastModified)
  return out
}

async function inspectScan(root: string, name: string): Promise<ScanInfo | null> {
  const overworld = path.join(root, 'region')
  const nether    = path.join(root, 'DIM-1', 'region')
  const end       = path.join(root, 'DIM1', 'region')

  const has = async (p: string) => {
    try { const s = await fsp.stat(p); return s.isDirectory() } catch { return false }
  }
  const countMca = async (p: string) => {
    try {
      const f = await fsp.readdir(p)
      return f.filter(n => n.endsWith('.mca')).length
    } catch { return 0 }
  }

  const [hasOverworld, hasNether, hasEnd] = await Promise.all([has(overworld), has(nether), has(end)])
  if (!hasOverworld && !hasNether && !hasEnd) return null

  const counts = await Promise.all([countMca(overworld), countMca(nether), countMca(end)])
  const regionFileCount = counts.reduce((a, b) => a + b, 0)
  if (regionFileCount === 0) return null

  let lastModified = 0
  try { lastModified = (await fsp.stat(root)).mtimeMs } catch {}

  return { name, path: root, hasOverworld, hasNether, hasEnd, regionFileCount, lastModified }
}

export function defaultSavesDir(): string {
  // Standard Windows MC location; user can override at transform time.
  const appdata = process.env.APPDATA
  if (appdata) return path.join(appdata, '.minecraft', 'saves')
  // mac/linux fallbacks
  if (process.platform === 'darwin') return path.join(os.homedir(), 'Library', 'Application Support', 'minecraft', 'saves')
  return path.join(os.homedir(), '.minecraft', 'saves')
}

export interface TransformOpts {
  scanPath: string              // source folder (one of the entries from listScans)
  destName: string              // target world name inside saves/
  savesDir?: string             // override Minecraft saves location
  voidUnscanned: boolean        // make missing chunks render as void instead of vanilla terrain
}

export interface TransformResult {
  ok: boolean
  destPath?: string
  outputCopyPath?: string
  error?: string
}

function defaultOutputDir(): string {
  return path.join(os.homedir(), 'Documents', 'ChunkScribe', 'worlds')
}

/**
 * Copy a scan into Minecraft's saves folder so it shows up in singleplayer.
 * Optionally rewrites level.dat to use a void worldgen, so chunks you never
 * captured stay empty instead of being regenerated by vanilla worldgen — same
 * effect as mircokroon's tool.
 */
export async function transformToWorld(opts: TransformOpts): Promise<TransformResult> {
  const savesDir = opts.savesDir || defaultSavesDir()
  const cleanName = sanitizeName(opts.destName) || 'ChunkScribe World'
  const destPath = path.join(savesDir, cleanName)

  try {
    if (!(await fsp.stat(opts.scanPath)).isDirectory()) {
      return { ok: false, error: 'scan path is not a directory' }
    }
  } catch {
    return { ok: false, error: 'scan path does not exist' }
  }

  try {
    await fsp.mkdir(savesDir, { recursive: true })
    // Refuse to overwrite an existing world — too easy to clobber by accident.
    try {
      await fsp.access(destPath)
      return { ok: false, error: `"${cleanName}" already exists in saves; pick a different name` }
    } catch {}
    await fsp.cp(opts.scanPath, destPath, { recursive: true })
    log.info(`transformed ${opts.scanPath} -> ${destPath}`)
  } catch (e) {
    return { ok: false, error: `copy failed: ${(e as Error).message}` }
  }

  if (opts.voidUnscanned) {
    try {
      await patchLevelDatForVoid(destPath, cleanName)
      log.info(`level.dat patched to void-around-scanned`)
    } catch (e) {
      log.warn(`void-patch failed: ${(e as Error).message}`)
    }
  } else {
    try {
      await patchLevelDatName(destPath, cleanName)
    } catch (e) {
      log.warn(`level.dat rename failed: ${(e as Error).message}`)
    }
  }

  // Secondary copy into Documents/ChunkScribe/worlds/<name> so the user keeps
  // a portable archive even after MC's saves folder rotates or they delete
  // the singleplayer world.
  let outputCopyPath: string | undefined
  try {
    const outRoot = defaultOutputDir()
    await fsp.mkdir(outRoot, { recursive: true })
    const outPath = path.join(outRoot, cleanName)
    // overwrite-safe: drop any prior copy with the same name first
    try { await fsp.rm(outPath, { recursive: true, force: true }) } catch {}
    await fsp.cp(destPath, outPath, { recursive: true })
    outputCopyPath = outPath
    log.info(`also copied to output archive: ${outPath}`)
  } catch (e) {
    log.warn(`output-archive copy failed: ${(e as Error).message}`)
  }

  return { ok: true, destPath, outputCopyPath }
}

function sanitizeName(s: string): string {
  return s.replace(/[\\\/:*?"<>|]+/g, '_').trim()
}

let nbt: any
try { nbt = require('prismarine-nbt') } catch {}

async function readLevelDat(dir: string): Promise<any | null> {
  if (!nbt) return null
  const p = path.join(dir, 'level.dat')
  let buf: Buffer
  try { buf = await fsp.readFile(p) } catch { return null }
  const raw = buf[0] === 0x1f && buf[1] === 0x8b ? await gunzip(buf) : buf
  return nbt.parseUncompressed(raw, 'big')
}

async function writeLevelDat(dir: string, tag: any) {
  const uncompressed = nbt.writeUncompressed(tag, 'big')
  const data: Buffer = Buffer.isBuffer(uncompressed) ? uncompressed : Buffer.from(uncompressed)
  const gz = await gzip(data)
  await fsp.writeFile(path.join(dir, 'level.dat'), gz)
}

async function patchLevelDatName(dir: string, name: string) {
  if (!nbt) return
  const tag = await readLevelDat(dir); if (!tag) return
  const data = tag.value?.Data?.value
  if (!data) return
  data.LevelName = { type: 'string', value: name }
  await writeLevelDat(dir, tag)
}

/**
 * Replace the overworld dimension generator with a void-flat preset so any
 * chunk the player visits that ISN'T in the captured region files stays
 * empty (a few barrier-less air layers), instead of being generated fresh
 * with vanilla terrain. Mircokroon's tool does the same trick.
 */
async function patchLevelDatForVoid(dir: string, name: string) {
  if (!nbt) return
  const tag = await readLevelDat(dir)
  if (!tag) return
  const data = tag.value?.Data?.value
  if (!data) return

  data.LevelName = { type: 'string', value: name }

  // Build the dimensions compound with a void-flat overworld + nether + end.
  // We have to enumerate all three so vanilla doesn't fall back to defaults.
  data.WorldGenSettings = {
    type: 'compound',
    value: {
      seed: data.WorldGenSettings?.value?.seed ?? { type: 'long', value: [0, 0] },
      generate_features: { type: 'byte', value: 0 },
      dimensions: {
        type: 'compound',
        value: {
          'minecraft:overworld':   voidDimension('minecraft:overworld'),
          'minecraft:the_nether':  voidDimension('minecraft:the_nether'),
          'minecraft:the_end':     voidDimension('minecraft:the_end'),
        },
      },
    },
  }

  await writeLevelDat(dir, tag)
}

function voidDimension(typeId: string): any {
  return {
    type: 'compound',
    value: {
      type: { type: 'string', value: typeId },
      generator: {
        type: 'compound',
        value: {
          type:     { type: 'string', value: 'minecraft:flat' },
          settings: {
            type: 'compound',
            value: {
              biome:    { type: 'string', value: 'minecraft:the_void' },
              features: { type: 'byte', value: 0 },
              lakes:    { type: 'byte', value: 0 },
              layers:   { type: 'list', value: { type: 'end', value: [] } },
              structure_overrides: { type: 'list', value: { type: 'end', value: [] } },
            },
          },
        },
      },
    },
  }
}
